[build]
  publish = "."
  command = ""
[[headers]]
  for = "/site-data.js"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
